{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gistr
  version: {{ version|replace("-", "_") }}

source:
  fn: gistr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gistr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gistr/gistr_{{ version }}.tar.gz
  sha256: a9e896703773aac8b49dc4a5b3db2fd0bf31afb9bc0dd3b32b6402ef74b9691e

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-httr >=1.2.0
    - r-jsonlite >=1.4
    - r-knitr
    - r-magrittr
    - r-rmarkdown
  run:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-httr >=1.2.0
    - r-jsonlite >=1.4
    - r-knitr
    - r-magrittr
    - r-rmarkdown

test:
  commands:
    - $R -e "library('gistr')"           # [not win]
    - "\"%R%\" -e \"library('gistr')\""  # [win]

about:
  home: https://github.com/ropensci/gistr
  license: MIT
  license_file: LICENSE
  summary: 'Work with ''GitHub'' ''gists'' from ''R'' (e.g.,  <http://en.wikipedia.org/wiki/GitHub#Gist>,  <https://help.github.com/articles/about-gists/>).
    A ''gist'' is simply one or more files with code/text/images/etc. This package allows
    the user to create new ''gists'', update ''gists'' with new files, rename files,
    delete files, get and delete ''gists'', star and ''un-star'' ''gists'', fork ''gists'',
    open a ''gist'' in your default browser, get embed code for a ''gist'', list ''gist''
    ''commits'', and get rate limit information when ''authenticated''. Some requests
    require authentication and some do not. ''Gists'' website:  <https://gist.github.com/>.'
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
